name='srisanth'
# print(len(name))
# print(name.find('a'))
# print(name.capitalize())
# print(name.upper())
# print(name.lower())
# print(name.isdigit())
# print(name.isalpha())
# print(name.count('s'))
# print(name.replace('s','q'))
print(name*3)
